//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBarbers.MainServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USER_", Namespace="http://schemas.datacontract.org/2004/07/ResBarbers_Backend")]
    [System.SerializableAttribute()]
    public partial class USER_ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AboutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Addressline1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Addressline2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Addressline3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.Appointment[] AppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.Appointment[] Appointments1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistories1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassPhraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.Review[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.Review[] Reviews1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniversityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserDOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string About {
            get {
                return this.AboutField;
            }
            set {
                if ((object.ReferenceEquals(this.AboutField, value) != true)) {
                    this.AboutField = value;
                    this.RaisePropertyChanged("About");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressline1 {
            get {
                return this.Addressline1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Addressline1Field, value) != true)) {
                    this.Addressline1Field = value;
                    this.RaisePropertyChanged("Addressline1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressline2 {
            get {
                return this.Addressline2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Addressline2Field, value) != true)) {
                    this.Addressline2Field = value;
                    this.RaisePropertyChanged("Addressline2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressline3 {
            get {
                return this.Addressline3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Addressline3Field, value) != true)) {
                    this.Addressline3Field = value;
                    this.RaisePropertyChanged("Addressline3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.Appointment[] Appointments {
            get {
                return this.AppointmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointmentsField, value) != true)) {
                    this.AppointmentsField = value;
                    this.RaisePropertyChanged("Appointments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.Appointment[] Appointments1 {
            get {
                return this.Appointments1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Appointments1Field, value) != true)) {
                    this.Appointments1Field = value;
                    this.RaisePropertyChanged("Appointments1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistories {
            get {
                return this.ClientBarberHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientBarberHistoriesField, value) != true)) {
                    this.ClientBarberHistoriesField = value;
                    this.RaisePropertyChanged("ClientBarberHistories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistories1 {
            get {
                return this.ClientBarberHistories1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientBarberHistories1Field, value) != true)) {
                    this.ClientBarberHistories1Field = value;
                    this.RaisePropertyChanged("ClientBarberHistories1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassPhrase {
            get {
                return this.PassPhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.PassPhraseField, value) != true)) {
                    this.PassPhraseField = value;
                    this.RaisePropertyChanged("PassPhrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidenceName {
            get {
                return this.ResidenceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenceNameField, value) != true)) {
                    this.ResidenceNameField = value;
                    this.RaisePropertyChanged("ResidenceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.Review[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.Review[] Reviews1 {
            get {
                return this.Reviews1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reviews1Field, value) != true)) {
                    this.Reviews1Field = value;
                    this.RaisePropertyChanged("Reviews1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string University {
            get {
                return this.UniversityField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversityField, value) != true)) {
                    this.UniversityField = value;
                    this.RaisePropertyChanged("University");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserDOB {
            get {
                return this.UserDOBField;
            }
            set {
                if ((this.UserDOBField.Equals(value) != true)) {
                    this.UserDOBField = value;
                    this.RaisePropertyChanged("UserDOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPicture {
            get {
                return this.UserPictureField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPictureField, value) != true)) {
                    this.UserPictureField = value;
                    this.RaisePropertyChanged("UserPicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appointment", Namespace="http://schemas.datacontract.org/2004/07/ResBarbers_Backend")]
    [System.SerializableAttribute()]
    public partial class Appointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AppointmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppointmentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan AppointmentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StyleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.USER_ USER_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.USER_ USER_1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AppointmentDate {
            get {
                return this.AppointmentDateField;
            }
            set {
                if ((this.AppointmentDateField.Equals(value) != true)) {
                    this.AppointmentDateField = value;
                    this.RaisePropertyChanged("AppointmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentID {
            get {
                return this.AppointmentIDField;
            }
            set {
                if ((this.AppointmentIDField.Equals(value) != true)) {
                    this.AppointmentIDField = value;
                    this.RaisePropertyChanged("AppointmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppointmentStatus {
            get {
                return this.AppointmentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointmentStatusField, value) != true)) {
                    this.AppointmentStatusField = value;
                    this.RaisePropertyChanged("AppointmentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan AppointmentTime {
            get {
                return this.AppointmentTimeField;
            }
            set {
                if ((this.AppointmentTimeField.Equals(value) != true)) {
                    this.AppointmentTimeField = value;
                    this.RaisePropertyChanged("AppointmentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarberID {
            get {
                return this.BarberIDField;
            }
            set {
                if ((this.BarberIDField.Equals(value) != true)) {
                    this.BarberIDField = value;
                    this.RaisePropertyChanged("BarberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistories {
            get {
                return this.ClientBarberHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientBarberHistoriesField, value) != true)) {
                    this.ClientBarberHistoriesField = value;
                    this.RaisePropertyChanged("ClientBarberHistories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StyleID {
            get {
                return this.StyleIDField;
            }
            set {
                if ((this.StyleIDField.Equals(value) != true)) {
                    this.StyleIDField = value;
                    this.RaisePropertyChanged("StyleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.USER_ USER_ {
            get {
                return this.USER_Field;
            }
            set {
                if ((object.ReferenceEquals(this.USER_Field, value) != true)) {
                    this.USER_Field = value;
                    this.RaisePropertyChanged("USER_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.USER_ USER_1 {
            get {
                return this.USER_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.USER_1Field, value) != true)) {
                    this.USER_1Field = value;
                    this.RaisePropertyChanged("USER_1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBarberHistory", Namespace="http://schemas.datacontract.org/2004/07/ResBarbers_Backend")]
    [System.SerializableAttribute()]
    public partial class ClientBarberHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.Appointment AppointmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AppointmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan AppointmentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CancelDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> CancelTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanceledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FulfillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> FulfillTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FulfilledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HistoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PostponeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> PostponeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PostponedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan RequestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RevIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.Review ReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.USER_ USER_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.USER_ USER_1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.Appointment Appointment {
            get {
                return this.AppointmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointmentField, value) != true)) {
                    this.AppointmentField = value;
                    this.RaisePropertyChanged("Appointment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AppointmentDate {
            get {
                return this.AppointmentDateField;
            }
            set {
                if ((this.AppointmentDateField.Equals(value) != true)) {
                    this.AppointmentDateField = value;
                    this.RaisePropertyChanged("AppointmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentID {
            get {
                return this.AppointmentIDField;
            }
            set {
                if ((this.AppointmentIDField.Equals(value) != true)) {
                    this.AppointmentIDField = value;
                    this.RaisePropertyChanged("AppointmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan AppointmentTime {
            get {
                return this.AppointmentTimeField;
            }
            set {
                if ((this.AppointmentTimeField.Equals(value) != true)) {
                    this.AppointmentTimeField = value;
                    this.RaisePropertyChanged("AppointmentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarberID {
            get {
                return this.BarberIDField;
            }
            set {
                if ((this.BarberIDField.Equals(value) != true)) {
                    this.BarberIDField = value;
                    this.RaisePropertyChanged("BarberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CancelDate {
            get {
                return this.CancelDateField;
            }
            set {
                if ((this.CancelDateField.Equals(value) != true)) {
                    this.CancelDateField = value;
                    this.RaisePropertyChanged("CancelDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> CancelTime {
            get {
                return this.CancelTimeField;
            }
            set {
                if ((this.CancelTimeField.Equals(value) != true)) {
                    this.CancelTimeField = value;
                    this.RaisePropertyChanged("CancelTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Canceled {
            get {
                return this.CanceledField;
            }
            set {
                if ((this.CanceledField.Equals(value) != true)) {
                    this.CanceledField = value;
                    this.RaisePropertyChanged("Canceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FulfillDate {
            get {
                return this.FulfillDateField;
            }
            set {
                if ((this.FulfillDateField.Equals(value) != true)) {
                    this.FulfillDateField = value;
                    this.RaisePropertyChanged("FulfillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> FulfillTime {
            get {
                return this.FulfillTimeField;
            }
            set {
                if ((this.FulfillTimeField.Equals(value) != true)) {
                    this.FulfillTimeField = value;
                    this.RaisePropertyChanged("FulfillTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Fulfilled {
            get {
                return this.FulfilledField;
            }
            set {
                if ((this.FulfilledField.Equals(value) != true)) {
                    this.FulfilledField = value;
                    this.RaisePropertyChanged("Fulfilled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HistoryID {
            get {
                return this.HistoryIDField;
            }
            set {
                if ((this.HistoryIDField.Equals(value) != true)) {
                    this.HistoryIDField = value;
                    this.RaisePropertyChanged("HistoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PostponeDate {
            get {
                return this.PostponeDateField;
            }
            set {
                if ((this.PostponeDateField.Equals(value) != true)) {
                    this.PostponeDateField = value;
                    this.RaisePropertyChanged("PostponeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> PostponeTime {
            get {
                return this.PostponeTimeField;
            }
            set {
                if ((this.PostponeTimeField.Equals(value) != true)) {
                    this.PostponeTimeField = value;
                    this.RaisePropertyChanged("PostponeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Postponed {
            get {
                return this.PostponedField;
            }
            set {
                if ((this.PostponedField.Equals(value) != true)) {
                    this.PostponedField = value;
                    this.RaisePropertyChanged("Postponed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan RequestTime {
            get {
                return this.RequestTimeField;
            }
            set {
                if ((this.RequestTimeField.Equals(value) != true)) {
                    this.RequestTimeField = value;
                    this.RaisePropertyChanged("RequestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RevID {
            get {
                return this.RevIDField;
            }
            set {
                if ((this.RevIDField.Equals(value) != true)) {
                    this.RevIDField = value;
                    this.RaisePropertyChanged("RevID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.Review Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.USER_ USER_ {
            get {
                return this.USER_Field;
            }
            set {
                if ((object.ReferenceEquals(this.USER_Field, value) != true)) {
                    this.USER_Field = value;
                    this.RaisePropertyChanged("USER_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.USER_ USER_1 {
            get {
                return this.USER_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.USER_1Field, value) != true)) {
                    this.USER_1Field = value;
                    this.RaisePropertyChanged("USER_1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/ResBarbers_Backend")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RevIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Review1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.USER_ USER_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ResBarbers.MainServiceReference.USER_ USER_1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarberID {
            get {
                return this.BarberIDField;
            }
            set {
                if ((this.BarberIDField.Equals(value) != true)) {
                    this.BarberIDField = value;
                    this.RaisePropertyChanged("BarberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.ClientBarberHistory[] ClientBarberHistories {
            get {
                return this.ClientBarberHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientBarberHistoriesField, value) != true)) {
                    this.ClientBarberHistoriesField = value;
                    this.RaisePropertyChanged("ClientBarberHistories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RevID {
            get {
                return this.RevIDField;
            }
            set {
                if ((this.RevIDField.Equals(value) != true)) {
                    this.RevIDField = value;
                    this.RaisePropertyChanged("RevID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Review1 {
            get {
                return this.Review1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Review1Field, value) != true)) {
                    this.Review1Field = value;
                    this.RaisePropertyChanged("Review1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reviewer {
            get {
                return this.ReviewerField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewerField, value) != true)) {
                    this.ReviewerField = value;
                    this.RaisePropertyChanged("Reviewer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.USER_ USER_ {
            get {
                return this.USER_Field;
            }
            set {
                if ((object.ReferenceEquals(this.USER_Field, value) != true)) {
                    this.USER_Field = value;
                    this.RaisePropertyChanged("USER_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ResBarbers.MainServiceReference.USER_ USER_1 {
            get {
                return this.USER_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.USER_1Field, value) != true)) {
                    this.USER_1Field = value;
                    this.RaisePropertyChanged("USER_1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/ResBarbers_Backend")]
    [System.SerializableAttribute()]
    public partial class MenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BarberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StyleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StylePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarberID {
            get {
                return this.BarberIDField;
            }
            set {
                if ((this.BarberIDField.Equals(value) != true)) {
                    this.BarberIDField = value;
                    this.RaisePropertyChanged("BarberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleDescription {
            get {
                return this.StyleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleDescriptionField, value) != true)) {
                    this.StyleDescriptionField = value;
                    this.RaisePropertyChanged("StyleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StyleID {
            get {
                return this.StyleIDField;
            }
            set {
                if ((this.StyleIDField.Equals(value) != true)) {
                    this.StyleIDField = value;
                    this.RaisePropertyChanged("StyleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleImage {
            get {
                return this.StyleImageField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleImageField, value) != true)) {
                    this.StyleImageField = value;
                    this.RaisePropertyChanged("StyleImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleName {
            get {
                return this.StyleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleNameField, value) != true)) {
                    this.StyleNameField = value;
                    this.RaisePropertyChanged("StyleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StylePrice {
            get {
                return this.StylePriceField;
            }
            set {
                if ((this.StylePriceField.Equals(value) != true)) {
                    this.StylePriceField = value;
                    this.RaisePropertyChanged("StylePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainServiceReference.IMainService")]
    public interface IMainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/RegisterUser", ReplyAction="http://tempuri.org/IMainService/RegisterUserResponse")]
        bool RegisterUser(ResBarbers.MainServiceReference.USER_ user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/RegisterUser", ReplyAction="http://tempuri.org/IMainService/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(ResBarbers.MainServiceReference.USER_ user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Login", ReplyAction="http://tempuri.org/IMainService/LoginResponse")]
        int Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Login", ReplyAction="http://tempuri.org/IMainService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetUserType", ReplyAction="http://tempuri.org/IMainService/GetUserTypeResponse")]
        string GetUserType(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetUserType", ReplyAction="http://tempuri.org/IMainService/GetUserTypeResponse")]
        System.Threading.Tasks.Task<string> GetUserTypeAsync(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AddHairstyle", ReplyAction="http://tempuri.org/IMainService/AddHairstyleResponse")]
        bool AddHairstyle(ResBarbers.MainServiceReference.MenuItem StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AddHairstyle", ReplyAction="http://tempuri.org/IMainService/AddHairstyleResponse")]
        System.Threading.Tasks.Task<bool> AddHairstyleAsync(ResBarbers.MainServiceReference.MenuItem StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/RemoveHairstyle", ReplyAction="http://tempuri.org/IMainService/RemoveHairstyleResponse")]
        bool RemoveHairstyle(int StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/RemoveHairstyle", ReplyAction="http://tempuri.org/IMainService/RemoveHairstyleResponse")]
        System.Threading.Tasks.Task<bool> RemoveHairstyleAsync(int StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/EditHairstyle", ReplyAction="http://tempuri.org/IMainService/EditHairstyleResponse")]
        bool EditHairstyle(int StyleID, ResBarbers.MainServiceReference.MenuItem Hairstyle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/EditHairstyle", ReplyAction="http://tempuri.org/IMainService/EditHairstyleResponse")]
        System.Threading.Tasks.Task<bool> EditHairstyleAsync(int StyleID, ResBarbers.MainServiceReference.MenuItem Hairstyle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainServiceChannel : ResBarbers.MainServiceReference.IMainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceClient : System.ServiceModel.ClientBase<ResBarbers.MainServiceReference.IMainService>, ResBarbers.MainServiceReference.IMainService {
        
        public MainServiceClient() {
        }
        
        public MainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUser(ResBarbers.MainServiceReference.USER_ user) {
            return base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(ResBarbers.MainServiceReference.USER_ user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public int Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public string GetUserType(int UserID) {
            return base.Channel.GetUserType(UserID);
        }
        
        public System.Threading.Tasks.Task<string> GetUserTypeAsync(int UserID) {
            return base.Channel.GetUserTypeAsync(UserID);
        }
        
        public bool AddHairstyle(ResBarbers.MainServiceReference.MenuItem StyleID) {
            return base.Channel.AddHairstyle(StyleID);
        }
        
        public System.Threading.Tasks.Task<bool> AddHairstyleAsync(ResBarbers.MainServiceReference.MenuItem StyleID) {
            return base.Channel.AddHairstyleAsync(StyleID);
        }
        
        public bool RemoveHairstyle(int StyleID) {
            return base.Channel.RemoveHairstyle(StyleID);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveHairstyleAsync(int StyleID) {
            return base.Channel.RemoveHairstyleAsync(StyleID);
        }
        
        public bool EditHairstyle(int StyleID, ResBarbers.MainServiceReference.MenuItem Hairstyle) {
            return base.Channel.EditHairstyle(StyleID, Hairstyle);
        }
        
        public System.Threading.Tasks.Task<bool> EditHairstyleAsync(int StyleID, ResBarbers.MainServiceReference.MenuItem Hairstyle) {
            return base.Channel.EditHairstyleAsync(StyleID, Hairstyle);
        }
    }
}
