<%@ Page EnableEventValidation="true" Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="register_profile.aspx.cs" Inherits="ResBarbers.register_profile" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div class="row no-gutters justify-content-center">
        <div class="col-md-6 ">
            <div class="login-wrap w-100 p-md-5 p-4">
                <h2 class="mb-4">Profile</h2>
                <div class="row">

                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 text-center">
                                <h4>Choose Profile Photo</h4>
                                <input type="file" id="profile-photo-input" accept="image/*" style="display: none;">
                                <label for="profile-photo-input" class="btn btn-primary">Select Photo</label>
                                <img id="profile-photo-preview" src="#" alt="Profile Photo" class="profile-photo" style="display: none;">
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="label" for="uname">User Name</label>
                            <input type="text" class="form-control" name="uname" id="uname" placeholder="username">
                        </div>
                    </div>





                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="label" for="about">About Me</label>
                            <textarea name="about" class="form-control" id="about" cols="30" rows="4" placeholder="Short description about yourself"></textarea>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="label" for="password">Password</label>
                            <input type="password" class="form-control" name="password" id="password1" placeholder="password">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="label" for="password2">Confirm Password</label>
                            <input type="password" class="form-control" name="password2" id="password2" placeholder="confirm password">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">

                            <asp:Button type="submit" runat="server" ID="btnBackToRegister" Text="Back" class="btn" OnClick="OnBackToRegiserClick" />

                            <asp:Button type="submit" runat="server" ID="btnRegister" Text="Register" class="btn" OnClick="OnRegisterClick" />

                            <div class="submitting"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>


    <%-- this code was generated by ChatGPT --%>
    <script>
        document.getElementById('profile-photo-input').addEventListener('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById('profile-photo-preview').src = e.target.result;
                document.getElementById('profile-photo-preview').style.display = 'block';
            };
            reader.readAsDataURL(e.target.files[0]);
        });
    </script>
    <script>
        document.getElementById('profile-photo-input').addEventListener('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById('profile-photo-preview').src = e.target.result;
                document.getElementById('profile-photo-preview').style.display = 'block';
            };
            reader.readAsDataURL(e.target.files[0]);
        });
    </script>

</asp:Content>
