<%@ Page EnableEventValidation="true" Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="register_profile.aspx.cs" Inherits="ResBarbers.register_profile" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div class="row no-gutters justify-content-center" runat="server">
        <div class="col-md-6 ">
            <div class="login-wrap w-100 p-md-5 p-4">
                <h2 class="mb-4">Profile</h2>
                <div class="row">

                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 text-center">
                                <h4>Choose Profile Photo</h4>
                                <%--<input type="file" id="profilePhoto" accept="image/*" style="display: none;">--%>
                                <input class="form-control" name="image" type="file" id="profile_Photo" runat="server"/>                                
                                <%--<label for="profilePhoto" class="btn btn-primary">Select Photo</label>--%>
                                
                                <asp:Button id="preview" runat="server" Text="Preview photo" class="btn btn-primary" OnClick="OnPreview" />
                                <div id="previewPhoto" runat="server">
                                    <%-- image preview --%>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="label" for="uname">User Name</label>
                            <input type="text" class="form-control" id="uname" runat="server" placeholder="username">
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="label" for="about">About Me</label>
                            <textarea class="form-control" id="about" runat="server" cols="30" rows="4" placeholder="Short description about yourself"></textarea>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="label" for="password">Password</label>
                            <input type="password" class="form-control" id="password" runat="server" placeholder="password">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="label" for="password2">Confirm Password</label>
                            <input type="password" class="form-control"  id="password_confrim" runat="server" placeholder="confirm password">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">

                            <asp:Button type="submit" runat="server" ID="btnBackToRegister" Text="Back" class="btn" OnClick="OnBackToRegiserClick" />

                            <asp:Button type="submit" runat="server" ID="btnRegister" Text="Register" class="btn" OnClick="OnRegisterClick" />
                            <asp:Label class="label" runat="server" ID="failedRegister" ></asp:Label>

                            <div class="submitting"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <%-- this code was generated by ChatGPT --%>
    <script>
        document.getElementById('profilePhoto').addEventListener('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById('profile-photo-preview').src = e.target.result;
                document.getElementById('profile-photo-preview').style.display = 'block';
            };
            reader.readAsDataURL(e.target.files[0]);
        });
    </script>
    <script>
        document.getElementById('profilePhoto').addEventListener('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById('profile-photo-preview').src = e.target.result;
                document.getElementById('profile-photo-preview').style.display = 'block';
            };
            reader.readAsDataURL(e.target.files[0]);
        });
    </script>

</asp:Content>
